### ISSUE TITLE
Crop Results

### ISSUE THREAD

**Issue by rmammina** [jwagner/smartcrop-cli#11]
Trying to get an idea on how to get better results for cropping. Currently I'm using the cli, with opencv faceDetection setting.

Most of the times, the crop works great, but will occasionally get bad results. Was wondering what settings would help fix these issues. I've messed around with a few options, but they don't make much of a difference. 

Command
```
smartcrop --faceDetection --config ./config.json #{input_path} #{output_path}
```

Config File
```
{
  "width": 258,
  "height": 250
}
```

Here's a few examples of bad cropping.

**Original**
![image](https://cloud.githubusercontent.com/assets/978280/23035009/9f1e2a0e-f432-11e6-9aa7-7e7182467a6d.png)

**Cropped**
![image](https://cloud.githubusercontent.com/assets/978280/23035115/f7ba3d4c-f432-11e6-91a8-24f691c80236.png)

**Original**
![image](https://cloud.githubusercontent.com/assets/978280/23035094/e61da330-f432-11e6-86b7-222694e1fb5c.png)

**Cropped**
![image](https://cloud.githubusercontent.com/assets/978280/23035100/eb83b242-f432-11e6-9f8f-3d94adce3717.png)

**Comment by jwagner** [comment]
I haven't tested it but I expect the 'issue' with the first image is that smartcrop.js tries to avoid having details at the edges of the image too avoid making the image too cramped. You could change this by tweaking the edge weight.

In the second image the face is probably not correctly recognized by opencv. The face recognizer that smartcrop-cli uses is for head on faces so it probably has problems with a hoody + shades + hard shadows. If the face is recognized (in this case tracking.js seems to recognize it) the crop is as expected:

![selection_119](https://cloud.githubusercontent.com/assets/293536/23104060/bc3c4e7c-f6c6-11e6-843d-7ce1bbd9b42e.png)

I do have some plans to port [openface](https://cmusatyalab.github.io/openface/) to Javascript for better face detection and less hassle with the opencv dependency, but it's probably going to be a decent amount of work and not a priority right now.

**Comment by rmammina** [comment]
Thanks for the response. I'll tweak the edge weight and see how that works.
