### ISSUE TITLE
opencv prerequisites

### ISSUE THREAD

**Issue by marcuslindblom** [jwagner/smartcrop-cli#14]
I'm trying to use smartcrop-cli using `npm install -g smartcrop-cli`. But I can't get faceDetection to work. What are the prerequisites for and how do I install opencv so it works with smartcrop-cli?

**Comment by jwagner** [comment]
You need to install [node-opencv](https://github.com/peterbraden/node-opencv) and it's dependencies. The details depend on your platform.
