### ISSUE TITLE
OpenCV error when using the http protocol

### ISSUE THREAD

**Issue by marcuslindblom** [jwagner/smartcrop-cli#17]
I try to run this command:
`smartcrop --width 300 --height 100 --faceDetection http://example.com/image.jpg` but I end up with an error like this:
```
OpenCV Error: Bad flag (parameter or structure field) (Unrecognized or unsupported array type) in cvGetMat, file /tmp/opencv-3.2.0/modules/core/src/array.cpp, line 2501
Error: /tmp/opencv-3.2.0/modules/core/src/array.cpp:2501: error: (-206) Unrecognized or unsupported array type in function cvGetMat

    at Error (native)
```
If i pipe the stream to smartcrop it works like excpected.

**Comment by jwagner** [comment]
What makes you think that this should work?

**Comment by marcuslindblom** [comment]
@jwagner You mean using the HTTP protocol to fetch the image? It works with ImageMagick so I was hoping that it would play nice with smartcrop

**Comment by jwagner** [comment]
It doesn't. If you need it you could curl http://..|smartcrop -
