### ISSUE TITLE
OpenCV problem when installing

### ISSUE THREAD

**Issue by Irraky** [jwagner/smartcrop-cli#18]
Hello,
I can use the project on image but can't use it with openCV.
I tried to change my node version to v6.10.3,  v8.9.1 and v8.11.2

I also installed open CV with: https://www.learnopencv.com/install-opencv3-on-ubuntu/#genesis-nav-primary 

Did I missed something?

When try to install it with openCV, I get this error: 
`node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@10.3.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@10.3.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
make : on entre dans le répertoire « /home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv/build »
 CXX(target) Release/obj.target/opencv/src/init.o
make : on entre dans le répertoire « /home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv/build »
 CXX(target) Release/obj.target/opencv/src/init.o
 CXX(target) Release/obj.target/opencv/src/Matrix.o
rm: impossible de supprimer './Release/.deps/Release/obj.target/opencv/src/init.o.d.raw': Aucun fichier ou dossier de ce type
opencv.target.mk:118 : la recette pour la cible « Release/obj.target/opencv/src/init.o » a échouée
make: *** [Release/obj.target/opencv/src/init.o] Erreur 1
make : on quitte le répertoire « /home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack   at ChildProcess.onExit (/home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack   at ChildProcess.emit (events.js:182:13)
gyp ERR! stack   at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.13.0-46-generic
gyp ERR! command "/home/irraky/.nvm/versions/node/v10.3.0/bin/node" "/home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv/build/opencv/v6.0.0/Release/node-v64-linux-x64/opencv.node" "--module_name=opencv" "--module_path=/home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv/build/opencv/v6.0.0/Release/node-v64-linux-x64"
gyp ERR! cwd /home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/irraky/.nvm/versions/node/v10.3.0/bin/node /home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv/build/opencv/v6.0.0/Release/node-v64-linux-x64/opencv.node --module_name=opencv --module_path=/home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv/build/opencv/v6.0.0/Release/node-v64-linux-x64' (1)
node-pre-gyp ERR! stack   at ChildProcess.<anonymous> (/home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack   at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack   at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack   at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Linux 4.13.0-46-generic
node-pre-gyp ERR! command "/home/irraky/.nvm/versions/node/v10.3.0/bin/node" "/home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv
node-pre-gyp ERR! node -v v10.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/home/irraky/.nvm/versions/node/v10.3.0/bin/node /home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv/build/opencv/v6.0.0/Release/node-v64-linux-x64/opencv.node --module_name=opencv --module_path=/home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv/build/opencv/v6.0.0/Release/node-v64-linux-x64' (1)
In file included from ../src/Contours.h:1:0,
         from ../src/Matrix.cc:1:
../src/OpenCV.h:32:10: fatal error: nan.h: Aucun fichier ou dossier de ce type
 #include <nan.h>
     ^~~~~~~
compilation terminated.
opencv.target.mk:118 : la recette pour la cible « Release/obj.target/opencv/src/Matrix.o » a échouée
make: *** [Release/obj.target/opencv/src/Matrix.o] Erreur 1
make : on quitte le répertoire « /home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack   at ChildProcess.onExit (/home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack   at ChildProcess.emit (events.js:182:13)
gyp ERR! stack   at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.13.0-46-generic
gyp ERR! command "/home/irraky/.nvm/versions/node/v10.3.0/bin/node" "/home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv/build/opencv/v6.0.0/Release/node-v64-linux-x64/opencv.node" "--module_name=opencv" "--module_path=/home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv/build/opencv/v6.0.0/Release/node-v64-linux-x64"
gyp ERR! cwd /home/irraky/.nvm/versions/node/v10.3.0/lib/node_modules/smartcrop-cli/node_modules/opencv
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN opencv@6.0.0 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: opencv@6.0.0 (node_modules/smartcrop-cli/node_modules/opencv):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
+ smartcrop-cli@2.0.3
updated 1 package in 14.75s`

**Comment by jwagner** [comment]
I'm not exactly sure what is causing this. Please check with the node-opencv docs.
