### ISSUE TITLE
Flag syntax to forward options from the CLI to smartcrop.js

### ISSUE THREAD

**Issue by mrzool** [jwagner/smartcrop-cli#19]
Hey @jwagner, I have one more question (related to [this one](https://github.com/jwagner/smartcrop.js/issues/85)): what is the correct flag syntax to pass options from `smartcrop-cli` to `smartcrop.js`, in my particular case `minScale`?

I've tried with `--minScale 1`, `-minScale 1` and `-minScale:1` — none of these seem to work.

I find the readme to be a bit unclear on this:

      -*               forwarded as options to smartcrop.js

Thanks a lot!

**Comment by mrzool** [comment]
Hey @jwagner, can it be assumed that the CLI flag to forward arbitrary options to `smartcrop.js` is broken? That feature would save me and my colleagues days of work in the months ahead. Would love to hear what you think.

**Comment by jwagner** [comment]
```jonas@fractal:~/dev/products/smartcrop-cli (master)$ smartcrop cat.jpg --ruleOfThirds 1
{
  "topCrop": {
    "x": 168,
    "y": 0,
    "width": 341,
    "height": 341,
    "score": {
      "detail": 156.98104573860218,
      "saturation": 8.230937417899083,
      "skin": 39.351382045996296,
      "boost": 0,
      "total": 0.0009003876648453616
    }
  }
}
jonas@fractal:~/dev/products/smartcrop-cli (master)$ smartcrop cat.jpg --ruleOfThirds 0
{
  "topCrop": {
    "x": 160,
    "y": 0,
    "width": 341,
    "height": 341,
    "score": {
      "detail": 49.99237500555963,
      "saturation": 3.8957294035759316,
      "skin": 8.272754152846115,
      "boost": 0,
      "total": 0.00022409638115691917
    }
  }
}
```
@mrzool seems to work just fine to me.
