### ISSUE TITLE
EOF ERROR

### ISSUE THREAD

**Issue by FelipeGerolomo** [jwagner/smartcrop-cli#21]
`var express = require('express');
var router = express.Router();
var uploads = require('./upload');
var request = require('request');
var gm = require('gm').subClass({ imageMagick: true });
var smartcrop = require('smartcrop-gm');

var src = 'https://raw.githubusercontent.com/jwagner/smartcrop-gm/master/test/flower.jpg';
applySmartCrop(src, 'public/images/', 300, 300);

function applySmartCrop(src, dest, width, height) {
  request(src, { encoding: null }, function process(error, response, body) {
    //if (error) return console.error(error);

    smartcrop.crop(body, { width: 100, height: 100 }).then((err, result) => {
      var crop = result.topCrop;
      gm(body)
        .crop(crop.width, crop.height, crop.x, crop.y)
        .resize(width, height)
        .write(dest, function(error) {
          if (error) return console.error(error);
        });
    }).catch(error => {
      console.log("erro", error)
    })
  });
}

module.exports = router;

OUTPUT: 
{ Error: write EOF
    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14) errno: 'EOF', code: 'EOF', syscall: 'write' }`

**Comment by jwagner** [comment]
That's smartcrop-gm not smartcrop-cli.
