### ISSUE TITLE
How to use with node smartcrop-gm?

### ISSUE THREAD

**Issue by mhulse** [jwagner/smartcrop-cli#8]
Hi! Thanks so much for this awesome code.

I am using `smartcrop-gm` in a node project.

How do I implement face detection (and other features of the `cli`) in a node project running `smartcrop-gm`?

I hate to admit it, but the docs did not make this clear for me.

Sorry to be a bother.

**Comment by jwagner** [comment]
Just look at the code:
https://github.com/jwagner/smartcrop-cli/blob/master/smartcrop-cli.js#L100

I updated the readme to point to that. I hope it helps.

Cheers,
Jonas

**Comment by mhulse** [comment]
Definitely! I will dissect the code. 👍 

Appreciate your help!
